NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"


login_check:
    path: /login_check

api:
    type: rest
    resource: "routing_api.yml"
    
