# /app/config/routing_auth.yml

vehicule:
    type: rest
    resource: MainBundle\Controller\VehiculeController

reservation:
    type: rest
    resource: MainBundle\Controller\ReservationController

