NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"


login_check:
    path: /login_check


vehicule:
    type: rest
    resource: MainBundle\Controller\VehiculeController

reservation:
    type: rest
    resource: MainBundle\Controller\ReservationController

admin:
    type: rest
    resource: "routing_admin.yml"
    prefix: /admin
    
