NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"

login_check:
    path: /login_check

auth:
    type: rest
    resource: "routing_auth.yml"
    prefix: /auth

admin:
    type: rest
    resource: "routing_admin.yml"
    prefix: /admin
    
