#pour lauthentification (passe par JWT voir security.yml)
login_check:
    path: /login_check

#seuls les ROLE_USER ont accès à cette URL
auth:
    type: rest
    resource: "routing_auth.yml"
    prefix: /auth

#seuls les ROLE_ADMIN ont accès à cette URL
admin:
    type: rest
    resource: "routing_admin.yml"
    prefix: /admin
    
