# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        jwt:
            lexik_jwt:
                class: MainBundle\Security\User\WebserviceUser

    encoders:
        MainBundle\Security\User\WebserviceUser:
            algorithm: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - app.jwt_token_authenticator
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_parameter: username
                password_parameter: password

        auth:
            pattern:   ^/auth
            guard:
                authenticators:
                    - lexik_jwt_authentication.security.guard.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth,  roles: IS_AUTHENTICATED_FULLY }
