# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    #Utilisé pour le GUARD et s'assurer que le token est OK
    app.jwt_token_authenticator:
        class: MainBundle\Security\Guard\JWTTokenAuthenticator
        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
        calls:
            - [setDoctrine, ["@doctrine.orm.entity_manager"]]

    #Gère le payload (ce qui sera inclu dans le token JWT)
    acme_api.event.jwt_created_listener:
        class: MainBundle\EventListener\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }