<?php

namespace MainBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSumReservationsDayByDay()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT  
                    cal.date
                    , sum(case when cal.date between res.dateDebut and res.dateFin then 1 else 0 end ) nb_resa
                from MainBundle:Calendrier cal, MainBundle:Reservation res
                group by cal.date
                having sum(case when cal.date between res.dateDebut and res.dateFin then 1 else 0 end ) != 0
                order by cal.date'
            )
            ->getResult();
    }

    public function findRequete()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT 
                    cal.date
					, vehi.immatriculation
                    , sum(case when cal.date between res.dateDebut and res.dateFin then 1 else 0 end ) nb_resa
                from MainBundle:Calendrier cal, MainBundle:Reservation res
					left join res.vehicule vehi
                group by cal.date , vehi.immatriculation
                having sum(case when cal.date between res.dateDebut and res.dateFin then 1 else 0 end ) != 0
                order by cal.date'
            )->setMaxResults(9)
            ->getResult();
    }

}
