<?php

namespace MainBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSumReservationsDayByDay()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT  
                    cal.date
                    , sum(case when cal.date between res.dateDebut and res.dateFin then 1 else 0 end ) nb_resa
                FROM MainBundle:Calendrier cal, MainBundle:Reservation res
                GROUP BY cal.date
                HAVING sum(case when cal.date between res.dateDebut and res.dateFin then 1 else 0 end ) != 0
                ORDER BY cal.date'
            )
            ->getResult();
    }

    public function findMyReservations($email)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT res
                FROM MainBundle:Reservation res
                WHERE 
                    res.email = \''. $email .'\'
                    AND res.statut != \'Annulée\' 
                ORDER BY res.dateFin DESC'
            )
            ->getResult();
    }

    /**
     * Retourne les creneaux par vehicules pour une annee et un mois donne
    **/
    public function findCreneauxByAnneeMois(int $annee, int $mois)
    {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT 
                    vehi.immatriculation
                    ,cal.jour
                    , sum(case when cal.date between res.dateDebut and res.dateFin then 1 else 0 end ) is_reserve
                FROM MainBundle:Calendrier cal, MainBundle:Vehicule vehi
                    LEFT JOIN vehi.reservations res 
                        WITH res.statut != \'Annulée\' 
                WHERE cal.annee = '. $annee .' AND cal.mois = '. $mois .' 
                GROUP BY vehi.immatriculation, cal.jour 
                ORDER BY vehi.immatriculation, cal.jour'
            )
            ->getResult();
    }

}
